baseUrl = "https://blog.jessfraz.com/"
CanonifyUrls = true
languageCode = "en-us"
title = "Ramblings from Jessie"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	description = "The blog of Jessie Frazelle, hacker of all things: systems, kernels, operating systems, etc..."
